#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

if [ "$?" -eq 0 ]; then
  # if [ "$(expr substr $(uname -s) 1 5)" == "MINGW" ]; then
  #   exec < /dev/console
  #   node ./.husky/scripts/post-merge.js
  # else
  # fi
  exec < /dev/console
  node ./.husky/scripts/post-merge.js
else
  echo ""
fi
