#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ "$?" -eq 0 ]; then
  #  node ./.husky/scripts/post-merge.js
  currentBranch=$(git symbolic-ref --short HEAD)
  orightBranch=$(git reflog -1 | sed -e '/@\{\d+\}: merge (.*):/')
  echo
  echo "**** Running post-commit hook from branch $currentBranch"
  echo "**** Running post-commit hook from branch $orightBranch"
else
   echo ""
fi
